upstream project1_frontend {
    server another-project1-frontend:3000 max_fails=3 fail_timeout=30s;
    keepalive 64;
}

upstream project1_backend {
    server another-project1-backend:5000 max_fails=3 fail_timeout=30s;
    keepalive 64;
}
