server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = /project1 {
        # rewrite ^ /project1/ last;
        return 301 $scheme://$http_host/project1/;
    }

    location = / {
        return 302 /project1/;
    }

    location /project1/ {
        try_files $uri $uri/ /project1/index.html;
    }
}

