server {
    listen 443 ssl;
    server_name example_domain.com;

    ssl_certificate     /etc/nginx/ssl/example_domain.crt;
    ssl_certificate_key /etc/nginx/ssl/example_domain.key;

    include snippets/ssl.conf;
    include snippets/security.conf;

    include conf.d/locations/example_domain/*.conf;

    location / {
        proxy_pass https://example_domain_frontend;
        include snippets/proxy-static.conf;
    }
}

server {
    listen 443 ssl;
    server_name www.example_domain.com;

    ssl_certificate     /etc/nginx/ssl/example_domain.crt;
    ssl_certificate_key /etc/nginx/ssl/example_domain.key;

    include snippets/ssl.conf;
    include snippets/security.conf;

    include conf.d/locations/example_domain/*.conf;

    location / {
        proxy_pass https://example_domain_frontend;
        include snippets/proxy-static.conf;
    }
}

server {
    listen 443 ssl;
    server_name api.example_domain.com;

    ssl_certificate     /etc/nginx/ssl/example_domain.crt;
    ssl_certificate_key /etc/nginx/ssl/example_domain.key;

    include snippets/ssl.conf;
    include snippets/security.conf;

    location / {
        proxy_pass https://example_domain_backend;
        include snippets/proxy-ws.conf;
        proxy_pass_request_headers on;

    }
}