log_format main_ext
  '$remote_addr [$time_local] '
  '"$request" $status '
  'rt=$request_time '
  'up="$upstream_addr" '
  'urt="$upstream_response_time" '
  'host="$host"';

access_log /var/log/nginx/access.log main_ext;
error_log  /var/log/nginx/error.log warn;
