# API + WebSocket
include snippets/proxy-base.conf;

# WebSocket
proxy_set_header Upgrade    $http_upgrade;
proxy_set_header Connection $connection_upgrade;

proxy_connect_timeout 5s;
proxy_read_timeout 3600s;
proxy_send_timeout 3600s;

proxy_buffering off;
