location /project1/ { # /project1/ or /project1  follow framework of project
    proxy_pass http://project1_frontend;  # upstream nginx or ip (http://172.16.1.13:80)
    include snippets/proxy-static.conf;
}